// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Threading;
using BlitzerCore.Utilities;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

using NUnit.Framework;

namespace AutomatedTests
{
    public class Opportunity : AutomationBase
    {
        public Opportunity(IWebDriver aWebDriver) : base (aWebDriver)
        {
            WebBot = aWebDriver;
        }

        public void Create()
        {
            Create(WebBot);
        }

        public void Create(IWebDriver aWebBot = null)
        {
            IWebDriver lWebBot = aWebBot;
            if (aWebBot == null)
                lWebBot = WebBot;

            lWebBot.FindElement(By.LinkText("New")).Click();
            lWebBot.FindElement(By.Id("Contacts_0__First")).Click();
            lWebBot.FindElement(By.Id("Contacts_0__First")).SendKeys("First_TestName");
            lWebBot.FindElement(By.Id("Contacts_0__Last")).Click();
            lWebBot.FindElement(By.Id("Contacts_0__Last")).SendKeys("Last_TestName");
            lWebBot.FindElement(By.Id("Contacts_0__DOB")).Click();
            lWebBot.FindElement(By.Id("Contacts_0__DOB")).SendKeys("10/10/1960");
            lWebBot.FindElement(By.Id("Contacts_0__PrimaryEmail")).Click();
            lWebBot.FindElement(By.Id("Contacts_0__PrimaryEmail")).SendKeys("JohnDoe@gmail.com");
            lWebBot.FindElement(By.Id("Contacts_0__Cell")).Clear();
            lWebBot.FindElement(By.Id("Contacts_0__Cell")).SendKeys("12344455555");
            lWebBot.FindElement(By.CssSelector(".mx-0:nth-child(2)")).Click();
            lWebBot.FindElement(By.Id("StartDate")).Clear();
            lWebBot.FindElement(By.Id("StartDate")).SendKeys("3/1/2022");
            lWebBot.FindElement(By.Id("DepartureCityCode")).SendKeys("RDU");
            lWebBot.FindElement(By.Id("EndDate")).Clear();
            lWebBot.FindElement(By.Id("EndDate")).SendKeys("3/9/2022");
            lWebBot.FindElement(By.Id("DestinationCityCode")).SendKeys("CUN");
            lWebBot.FindElement(By.Id("RefferalId")).Click();
            {
                var dropdown = lWebBot.FindElement(By.Id("RefferalId"));
                dropdown.FindElement(By.XPath("//option[. = 'Facebook']")).Click();
            }
            lWebBot.FindElement(By.Id("Notes")).Click();
            lWebBot.FindElement(By.Id("Notes")).SendKeys("This is a Note");
            // Save the Opportunity
            lWebBot.FindElement(By.XPath(OPPORTUNITY_SAVE_BTN)).Click();
            lWebBot.FindElement(By.XPath(DASHBOARD_XPATH)).Click();
            // Click the Dashboard LInk
        }

        public void CreateManualQuote()
        {
            // Click the First Row Opportunity on the main screen
            ClickButtonUsingXPath(FIRST_ROW_OPPORTUNITY);
            // Click the edit button for the Quote Request
            ClickButtonUsingXPath( QUOTEREQUEST_FIRST_ROW_EDIT_BTN);
            // Click the manual Quote button
            WebBot.FindElement(By.CssSelector(".col-2:nth-child(1) > input")).Click();
            // 4 | click | id=TourOperatorID |  | 
            SelectByText(WebBot, "TourOperatorID", "Vacation Express (800) 309-4717");
            SelectByText(WebBot, "SupplierId", "Atelier Playa Mujeres");
            Thread.Sleep(200);
            ClickLinkById("SKUID");
            SelectByText(WebBot, "SKUID", "Inspira Rooftop Suite");
            InputTextByName("PackagePrice", "5500");
            InputTextByName("Adjustment", "150");
            WebBot.FindElement(By.Id("Insurance")).Click();
            SelectByText(WebBot, "Status", "Ready");
            // Click the Save button on the Manal Quote Screen
            WebBot.FindElement(By.CssSelector(".btn-primary")).Click();
            // Return to the main screen
            WebBot.FindElement(By.XPath(DASHBOARD_XPATH)).Click();

        }

        protected static void SelectByText(IWebDriver aWebBot, string aElementId, string aListText )
        {
            var lList = aWebBot.FindElement(By.Id(aElementId));
            lList.Click();
            // 5 | select | id=TourOperatorID | label=Vacation Express (800) 309-4717 | 
            {
                SelectElement lTourOpList = new SelectElement(lList);
                lTourOpList.SelectByText(aListText);
            }
        }

        /// <summary>
        /// Prerect : Must be on main page to execute
        /// </summary>
        /// <param name="aWebBot"></param>
        public void PullQuotes(IWebDriver aWebBot = null)
        {
            IWebDriver lWebBot = aWebBot;
            if (aWebBot == null)
                lWebBot = WebBot;

            while ( lWebBot.FindElement(By.XPath(FIRST_ROW_OPPORTUNITY)) == null ) 
                Thread.Sleep(500);

            lWebBot.FindElement(By.XPath(FIRST_ROW_OPPORTUNITY)).Click();
            // Execute Search
            lWebBot.FindElement(By.XPath(QUOTEREQUEST_FIRST_ROW_EDIT_BTN)).Click();
            // Click the Pull Quotes button 
            lWebBot.FindElement(By.XPath(PULLQUOTES_BTN)).Click();
            // Click the Dashboard LInk
            lWebBot.FindElement(By.XPath(DASHBOARD_XPATH)).Click();

        }
    }
}
