// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using BlitzerCore.Helpers;
using Microsoft.VisualStudio.TestPlatform.ObjectModel;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace AutomatedTests
{
    [TestFixture]
    public class FilterHotelsTest : AutomationBase

    {

        [Test]
    public void Execute_Bot_Pull_And_ViewQuote()
    {
        new Security(WebBot).Login();
        new Opportunity(WebBot).Create();
        new Opportunity(WebBot).PullQuotes();
        FilterHotels();
        FilterSKUs();
        ViewBotQuote();
    }

    [Test]
    public void Create_Manual_Quote_And_ViewQuote()
    {
        new Security(WebBot).Login();
        new Opportunity(WebBot).Create();
        new Opportunity(WebBot).CreateManualQuote();
        ViewManualQuote();
    }

    public new void FilterHotels()
    {

        WebBot.FindElement(By.XPath(FIRST_ROW_OPPORTUNITY)).Click();
        WebBot.FindElement(By.LinkText("Edit")).Click();
        WebBot.FindElement(By.LinkText("Filter Resorts")).Click();
        // Select the Hyatt Zilara Cancun
        WebBot.FindElement(By.Id("Accommondations_61__Checked")).Click();
        // Selec tehe Hyatt Ziva Cancun
        WebBot.FindElement(By.Id("Accommondations_62__Checked")).Click();
        WebBot.FindElement(By.Id("Submit")).Click();
        WebBot.FindElement(By.CssSelector("div:nth-child(1) > a > span")).Click();
    }

    public void FilterSKUs()
    {
        ClickButtonUsingXPath(FIRST_ROW_OPPORTUNITY);
        WebBot.FindElement(By.LinkText("Edit")).Click();
        WebBot.FindElement(By.LinkText("Filter Sub Room Types")).Click();
        WebBot.FindElement(By.Id("SKUs_0__Checked")).Click();
        WebBot.FindElement(By.Id("SKUs_1__Checked")).Click();
        WebBot.FindElement(By.Id("SKUs_2__Checked")).Click();
        WebBot.FindElement(By.Id("SKUs_3__Checked")).Click();
        WebBot.FindElement(By.Id("SKUs_1__Checked")).Click();
        WebBot.FindElement(By.CssSelector("div:nth-child(1) > a > span")).Click();

    }

    public void ViewBotQuote()
    {
        ClickButtonUsingXPath(FIRST_ROW_OPPORTUNITY);
        WebBot.FindElement(By.LinkText("Edit")).Click();
        WebBot.FindElement(By.LinkText("Client View")).Click();
        var lWebElement = WebBot.FindElement(By.XPath(FIRST_HOTEL_BOT_PRICE));
        var lText = lWebElement.Text;
        Assert.AreEqual("$4,827.50", lText.Trim());

            lWebElement =
            WebBot.FindElement(
                By.XPath("//*[@id='ICQuote']/form/div[1]/div[6]/div[2]/div/div[2]/table/tbody/tr/td[2]"));
        lText = lWebElement.Text;
        Assert.AreEqual("$4,478.04", lText.Trim());

            // Return to Main Portal Screen
            WebBot.FindElement(By.XPath(PORTAL_LINK_XPATH)).Click();
    }

    public void ViewManualQuote()
    {
        ClickButtonUsingXPath(FIRST_ROW_OPPORTUNITY);
        WebBot.FindElement(By.LinkText("Edit")).Click();
        WebBot.FindElement(By.LinkText("Client View")).Click();
        var lWebElement = WebBot.FindElement(By.XPath(FIRST_HOTEL_BOT_PRICE));
        var lText = lWebElement.Text;
        Assert.AreEqual("$5,650.00", lText.Trim());

        // Return to Main Portal Screen
        WebBot.FindElement(By.XPath(PORTAL_LINK_XPATH)).Click();
    }

    public void AddManualQuote()
    {
        const double MANUALPRICE = 5200.37;
        const double SECONDBOTPRICE = 5200.37;

        const string MANUALPRICE_XPATH = "//*[@id='devextreme0']/div/div[6]/div/table/tbody/tr[5]/td[6]";
        const string FIRSTTO_XPATH = "//*[@id='devextreme0']/div/div[6]/div/table/tbody/tr[1]/td[1]";
        const string FIRSTSUPPLIER_XPATH = "//*[@id=devextreme0']/div/div[6]/div/table/tbody/tr[1]/td[2]";
        const string SECONDBOTPRICE_XPATH = "//*[@id='devextreme0']/div/div[6]/div/table/tbody/tr[2]/td[6]";
        WebBot.FindElement(By.XPath(OPPORTUNITY_XPATH)).Click();
        WebBot.FindElement(By.LinkText("Edit")).Click();
        WebBot.FindElement(By.CssSelector(".col-2:nth-child(1) > input")).Click();
        WebBot.FindElement(By.Id("TourOperatorID")).Click();
        {
            var dropdown = WebBot.FindElement(By.Id("TourOperatorID"));
            dropdown.FindElement(By.XPath("//option[. = 'Vacation Express (800) 309-4717']")).Click();
        }
        WebBot.FindElement(By.Id("SupplierId")).Click();
        {
            var dropdown = WebBot.FindElement(By.Id("SupplierId"));
            dropdown.FindElement(By.XPath("//option[. = 'Atelier Playa Mujeres']")).Click();
        }
        WebBot.FindElement(By.Id("SKUID")).Click();
        {
            var dropdown = WebBot.FindElement(By.Id("SKUID"));
            dropdown.FindElement(By.XPath("//option[. = 'Inspira Master Suite Ocean Front']")).Click();
        }
        WebBot.FindElement(By.Id("PackagePrice")).Clear();
        WebBot.FindElement(By.Id("PackagePrice")).SendKeys($"{MANUALPRICE}");
        WebBot.FindElement(By.Id("Status")).Click();
        {
            var dropdown = WebBot.FindElement(By.Id("Status"));
            dropdown.FindElement(By.XPath("//option[. = 'Ready']")).Click();
        }
        WebBot.FindElement(By.Id("Transfer")).Click();
        // Click Save button Manual Quote Screen
        WebBot.FindElement(By.CssSelector(".btn-primary")).Click();

        var lWebElement = WebBot.FindElement(By.XPath(MANUALPRICE_XPATH));
        var lText = lWebElement.Text;
        Assert.AreEqual(DataHelper.ConvertToCurrency(MANUALPRICE), lText.Trim());

        lWebElement = WebBot.FindElement(By.XPath(FIRSTTO_XPATH));
        lText = lWebElement.Text;
        Assert.AreEqual(DataHelper.ConvertToCurrency(MANUALPRICE), lText.Trim());

        lWebElement = WebBot.FindElement(By.XPath(FIRSTSUPPLIER_XPATH));
        lText = lWebElement.Text;
        Assert.AreEqual("Delta Vacations", lText);

        lWebElement = WebBot.FindElement(By.XPath(SECONDBOTPRICE_XPATH));
        lText = lWebElement.Text;
        Assert.AreEqual(DataHelper.ConvertToCurrency(SECONDBOTPRICE), lText.Trim());
    }
    }
}
