// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using BlitzerCore.WebBots;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

using NUnit.Framework;
using System.Net;
using BlitzerCore.Utilities;
using Microsoft.Net.Http.Headers;

namespace AutomatedTests
{
    public class Security : AutomationBase
    {
        private const string ClassName = "AutomatedTests::Security:";
        public Security(IWebDriver aWebDriver) : base( aWebDriver) {
         }

        public IWebDriver Login()
        {
            string FuncName = $"{ClassName}Login - ";
            if (Dns.GetHostName().ToUpper() == "HERCULES")
            {
                Console.WriteLine($"{FuncName}Attempting to connect to http://Horse");
                WebBot.Navigate().GoToUrl("http://localhost:53334/");
                //WebBot.Navigate().GoToUrl("http://Horse/");
            }
            else
            {
                Console.WriteLine($"{FuncName}Attempting to connect to http://Localhost");
                WebBot.Navigate().GoToUrl("http://LocalHost/");
            }


            Console.WriteLine("Check for already being logined in ");
            if (WebBot.FindElement(By.CssSelector("#main_menu > .menu-item:nth-child(4) > a")) == null)
            {
                Console.WriteLine("Loggin out ");
                WebBot.FindElement(By.LinkText("LOGOUT")).Click();
            }


            WaitForElement(By.CssSelector("#main_menu > .menu-item:nth-child(4) > a"));
            WebBot.FindElement(By.CssSelector("#main_menu > .menu-item:nth-child(4) > a")).Click();
            Console.WriteLine("clicking email field");
            Thread.Sleep(700);
            WebBot.FindElement(By.Id("Input_Email")).Click();
            Console.WriteLine("Sending Email Address");
            Thread.Sleep(700);
            WebBot.FindElement(By.Id("Input_Email")).SendKeys("eric@eze2travel.com");
            WebBot.FindElement(By.Id("Input_Password")).SendKeys("Test!1234");
            WebBot.FindElement(By.CssSelector(".btn")).Click();
            return WebBot;
        }
        public void LogOut()
        {
        }
    }
}
