# Starter pipeline
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/BlitzerCore.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      **/BlitzerCore.csproj
      **/WebApp.csproj
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- integration

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'Restore .Net Core'

 - task: DotNetCoreCLI@2
 inputs:
 command: restore
 projects: '**/*.csproj'
 feedsToUse: config
 nugetConfigPath: NuGet.config 
